routes/web.php
<?php

use App\Http\Controllers\WordController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('words', WordController::class);
// Route::get('/',[WordController::class, 'index'])->name('words.index');
Route::post('/range',[WordController::class, 'rangeCheck'])->name('words.rangeCheck');


Route::post('/setRange',[WordController::class, 'setRange'])->name('words.test.setRange');
Route::get('/test/{from}/{to}',[WordController::class, 'makeTestQuestion'])->name('words.test');
Route::get('/check/{from}/{to}',[WordController::class, 'checkWord'])->name('words.check');
Route::get('/mcq/{from}/{to}',[WordController::class, 'MCQ'])->name('words.mcq');
Route::get('/mcqPage/{from}/{to}',[WordController::class, 'MCQpage'])->name('words.mcqPage');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/Word.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Word extends Model
{
    use HasFactory;
    protected $guarded = [''];

    public function scopeSearch($query)
    {
        $search = request('search');
        if($search)
        {
            return $query->where('name','like',"%$search%");
        }
        return $query;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WordController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateWordRequest;
use App\Models\Word;
use Illuminate\Http\Request;

class WordController extends Controller
{
    public function setRange(Request $request)
    {
        $validated = request()->validate([
            'From-field-test' => 'required|numeric|gt:0',
            'To-field-test' => 'required|numeric|gt:0|gt:From-field-test',
            'type' => 'required'
        ]);
        $from = $validated['From-field-test'];
        $to = $validated['To-field-test'];
        if($request->type == 1)
            return redirect(route('words.test',[$from,$to]));
        elseif($request->type == 2)
            return redirect(route('words.check',[$from,$to]));
        elseif($request->type == 3)
            return redirect(route('words.mcq',[$from,$to]));
        elseif($request->type == 4)
            return redirect(route('words.mcqPage',[$from,$to]));
    }

    private function makeTest($request)
    {
        $checks = [$request->from,$request->to];
        $questions = Word::inRandomOrder()->whereBetween('id',$checks)->get();
        $question_paper = [];
        foreach($questions as $question)
        {
            $Otherwords = Word::inRandomOrder()->limit(3)->get();
            $meanings[] = [$question->meaning,$question->id];
            for($i=0; $i<3; $i++)
            {
                $meanings[] = [$Otherwords[$i]->meaning, $Otherwords[$i]->id];
            }
            shuffle($meanings);
            $meanings[] = $question->id;
            $question_paper[$question->name] = $meanings;
            $meanings = [];
        }
        return [$question_paper, $checks];
    }

    public function MCQ(Request $request)
    {
        $vals = $this->makeTest($request);
        return view('mcq',['question_paper' => $vals[0],'checks' => $vals[1]]);
    }

    public function MCQpage(Request $request)
    {
        $vals = $this->makeTest($request);
        return view('mcqPage',['question_paper' => $vals[0],'checks' => $vals[1]]);
    }

    public function makeTestQuestion(Request $request)
    {
        $checks = [$request->from,$request->to];
        $question = Word::inRandomOrder()->whereBetween('id',$checks)->first();
        $word = [$question->name, $question->id];
        $Otherwords = Word::inRandomOrder()->limit(3)->get();
        $meanings[] = [$question->meaning,$question->id];
        for($i=0; $i<3; $i++)
        {
            $meanings[] = [$Otherwords[$i]->meaning, $Otherwords[$i]->id];
        }
        shuffle($meanings);
        return view('test',[
            'word' => $word,
            'meanings' => $meanings,
            'checks' => $checks
        ]);
    }

    public function index()
    {
        $words = Word::search()->paginate(4);
        return view('index',['words'=> $words]);
    }

    public function rangeCheck()
    {

        $validated = request()->validate([
            'From-field' => 'required|numeric|gt:0',
            'To-field' => 'required|numeric|gt:0|gt:From-field',
        ]);
        $checks = array($validated['From-field'],$validated['To-field']);
        // dd($validated['From-field']);
        $words = Word::whereBetween('id',$checks)->get();
        return view('range',['words'=> $words]);
    }

    public function create()
    {
        return view('create');
    }

    public function store(CreateWordRequest $request)
    {

        Word::create([
            'name' => $request->name,
            'meaning' => $request->meaning
        ]);

        return redirect('/words/create/?q=success&op=add');
    }

    public function edit(int $id)
    {
        $word = Word::findOrFail($id);
        return view('edit',['word'=>$word]);
    }

    public function update(int $id)
    {
        $old = Word::findOrFail($id);
        $word = request()->validate([
            'name' => 'required',
            'meaning' => 'required'
        ]);
        $old->update($word);
        return redirect("/words/$old->id/edit/?q=success&op=edit");
    }

    public function checkWord(Request $request)
    {
        $checks = [$request->from,$request->to];
        $question = Word::inRandomOrder()->whereBetween('id',$checks)->first();
        return view('check',['word' => $question,'check' => $checks]);
    }
}

app/Http/Controllers/tempCodeRunnerFile.php
<?php
Word::inRandomOrder()->whereBetween('id',[$this->from,$this->to])->first()

resources/views/check.blade.php
@extends('layouts.app')
@section('content')


<div class="mt-3">
    <div class="card p-0">
        <div class="card-header bg-dark text-light">
          <p class="text-center font-weight-bold m-0">Word {{ $word->id }}</p>
        </div>
        <div class="card-body">
          <h1 class=" text-center card-title text-capitalize">{{ $word->name }}</h1>
          <p id="meaning" class="text-center card-text text-capitalize mt-3" style="display:none;">{{ $word->meaning }}</p>
          <div class="d-flex justify-content-center mt-5">
            <a id="btn-show" class="btn btn-primary text-light">Show</a>
            <a href="{{ route('words.check',$check) }}" class="btn btn-secondary ml-3 text-light">Next</a>
          </div>
        </div>
      </div>
</div>
@endsection

@section('footer-val','fixed-bottom')
@section('scripts')
<script>

    $('#btn-show').click(function(){
        $('#meaning').fadeIn("slow");
    });
</script>
@endsection

resources/views/create.blade.php
@extends('layouts.app')
@section('content')


    <div class="d-flex justify-content-center">
        <div class="card mt-5 w-75">
            <div class="card-header bg-dark text-light">
              <p class="font-weight-bold m-0">Add a new word</p>
            </div>
            <div class="card-body">

                <form action={{ route('words.store') }} method="POST">
                    @csrf
                    <div class="form-group">
                      <label for="name">Word</label>
                      <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}">
                      @error('name')
                          <small class="text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="meaning">Word Meaning</label>
                      <input type="text" name="meaning" class="form-control" id="meaning" value="{{ old('meaning') }}">
                      @error('meaning')
                          <small class="text-danger">{{ $message }}</small>
                      @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a id="clear" class="btn bg-secondary text-light">Clear</a>
                  </form>

            </div>
          </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card mt-3" id="success_card">
            <div class="card-body">
              <p class="text-success m-0">The word has beed added!</p>
        </div>
    </div>
    </div>


@endsection

@section('footer-val','fixed-bottom')
@section('scripts')
<script>
    $('#success_card').hide();
    <?php
    $q = "";
    $op = "";

    if(isset($_GET['q']))
    {
        $q = $_GET['q'];
    }
    if(isset($_GET['op']))
    {
        $op = $_GET['op'];
    }

    if($q == "success" && $op == "add")
    {
    ?>


            $('#success_card').show();

        setTimeout(function(){
            $('#success_card').hide();

        }, 2000);



    <?php
    }
    ?>
        </script>




<script>
    $('#clear').click(function(){
        $('#name').val(" ");
        $('#meaning').val(" ");
    });
</script>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')
@section('content')


    <div class="d-flex justify-content-center">
        <div class="card mt-5 w-75">
            <div class="card-header bg-dark text-light">
              <p class="font-weight-bold m-0">Edit word</p>
            </div>
            <div class="card-body">

                <form action={{ route('words.update',$word->id) }} method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                      <label for="name">Word</label>
                      <input type="text" name="name" class="form-control" id="name" value="{{ $word->name }}">
                      @error('name')
                          <small class="text-danger">{{ $message }}</small>
                      @enderror
                    </div>
                    <div class="form-group">
                      <label for="meaning">Word Meaning</label>
                      <input type="text" name="meaning" class="form-control" id="meaning" value="{{ $word->meaning }}">
                      @error('meaning')
                          <small class="text-danger">{{ $message }}</small>
                      @enderror
                    </div>

                    <button id="btn-edit" type="submit" class="btn btn-primary">Edit</button>
                    <a id="clear" class="btn bg-secondary text-light">Clear</a>
                  </form>

            </div>
          </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card mt-3" id="success_card">
            <div class="card-body">
              <p class="text-warning m-0">The word has beed edited!</p>
        </div>
    </div>
    </div>


@endsection

@section('footer-val','fixed-bottom')
@section('scripts')
<script>
    $('#btn-edit').hide();
    $('#name').keypress(function(){
        $('#btn-edit').show();
    });
    $('#meaning').keypress(function(){
        $('#btn-edit').show();
    });
</script>
<script>
    $('#success_card').hide();
    <?php
    $q = "";
    $op = "";

    if(isset($_GET['q']))
    {
        $q = $_GET['q'];
    }
    if(isset($_GET['op']))
    {
        $op = $_GET['op'];
    }

    if($q == "success" && $op == "edit")
    {
    ?>


            $('#success_card').show();

        setTimeout(function(){
            $('#success_card').hide();

        }, 3000);



    <?php
    }
    ?>
        </script>




<script>
    $('#clear').click(function(){
        $('#name').val(" ");
        $('#meaning').val(" ");
    });
</script>
@endsection

resources/views/index.blade.php
@extends('layouts.app')
@section('content')

      {{-- Index --}}
      @if($errors->any())
            <div class="mx-auto" style="width: 400px;">
                @foreach ($errors->all() as $error)
                <p class="text-danger m-0"> {{ $error }}</p>
            @endforeach
            </div>
        @endif
      <div class="range d-flex justify-content-center mt-3">
       <div>
        <form class="form-inline" action="{{ route('words.rangeCheck') }}" method="POST">
            @csrf
            <div class="form-group mx-sm-3 mb-2">
                <input type="number" class="form-control" id="from" name='From-field' placeholder="From" value="{{ old('From-field') }}">
              </div>
            <div class="form-group mx-sm-3 mb-2">
              <input type="number" class="form-control" id="to" name='To-field' placeholder="To" value="{{ old('To-field') }}">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Search</button>
          </form>
       </div>
     </div>



      <div class="row">
        @foreach ($words as $word)
        <div class="col-sm-6 mt-3">
            <div class="card p-0">
                <div class="card-header bg-dark text-light">
                  <p class="font-weight-bold m-0">Word {{ $word->id }}</p>
                </div>
                <div class="card-body">
                  <h2 class="card-title text-capitalize">{{ $word->name }}</h2>
                  <p class="card-text text-capitalize">{{ $word->meaning }}</p>
                  <a href="{{ route('words.edit', $word->id) }}" class="btn btn-warning">Edit</a>
                </div>
              </div>
        </div>
        @endforeach
      </div>

      <div class="pagination mt-3 d-flex justify-content-center">
        <div class="w-50">
            {{-- {{ $words->links('vendor.pagination.bootstrap-4') }} --}}
            {{ $words->appends(['search' => request('search')])->links('vendor.pagination.bootstrap-4') }}
        </div>
      </div>


@endsection

@section('footer-val','fixed-bottom')

resources/views/layouts/app.blade.php
    @include('layouts.navbar')

    <div class="container">
        @yield('content')
    </div>

    @include('layouts.modals')

    @include('layouts.footer')

resources/views/layouts/footer.blade.php
{{-- /Index --}}

</div>

{{-- Footer --}}
<footer class="@yield('footer-val')">
    <!-- Copyright -->
<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
 © 2021 Copyright
    <p class="font-weight-bold" style="display:inline">Smit Vaghela</p>
</div>
<!-- Copyright -->
</footer>
{{-- /Footer --}}


<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@yield('scripts')
<script>

</script>
</body>
</html>

resources/views/layouts/modals.blade.php
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Range for MCQs Check</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form  action="{{ route('words.test.setRange')}}"  method="POST">
            @csrf
            <div class="modal-body row">
                <div class="form-group col-6 mb-2 ">
                    <input type="number" class="form-control" id="from" name='From-field-test' placeholder="From" value="1">
                </div>
                <div class="form-group col-6 mb-2">
                  <input type="number" class="form-control" id="to" name='To-field-test' placeholder="To">
                </div>
                <input type="hidden" value="1" name="type">
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success" id="startTestbtn">Start Check</button>
            </div>
        </form>
      </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel2">Range for Show word Check</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form  action="{{ route('words.test.setRange')}}"  method="POST">
            @csrf
            <div class="modal-body row">
                <div class="form-group col-6 mb-2 ">
                    <input type="number" class="form-control" id="from" name='From-field-test' placeholder="From" value="1">
                </div>
                <div class="form-group col-6 mb-2">
                  <input type="number" class="form-control" id="to" name='To-field-test' placeholder="To">
                </div>
                <input type="hidden" value="2" name="type">
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success" id="startTestbtn">Start Check</button>
            </div>
        </form>
      </div>
    </div>
</div>


<div class="modal fade" id="exampleModal3" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel3" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel3">Range for MCQs test</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form  action="{{ route('words.test.setRange')}}"  method="POST">
            @csrf
            <div class="modal-body row">
                <div class="form-group col-6 mb-2 ">
                    <input type="number" class="form-control" id="from" name='From-field-test' placeholder="From" value="1">
                </div>
                <div class="form-group col-6 mb-2">
                  <input type="number" class="form-control" id="to" name='To-field-test' placeholder="To">
                </div>
                <input type="hidden" value="3" name="type">
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success" id="startTestbtn">Start Test</button>
            </div>
        </form>
      </div>
    </div>
</div>

<div class="modal fade" id="exampleModal4" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel4" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel4">Range for Show word Test</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form  action="{{ route('words.test.setRange')}}"  method="POST">
            @csrf
            <div class="modal-body row">
                <div class="form-group col-6 mb-2 ">
                    <input type="number" class="form-control" id="from" name='From-field-test' placeholder="From" value="1">
                </div>
                <div class="form-group col-6 mb-2">
                  <input type="number" class="form-control" id="to" name='To-field-test' placeholder="To">
                </div>
                <input type="hidden" value="4" name="type">
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success" id="startTestbtn">Start Test</button>
            </div>
        </form>
      </div>
    </div>
</div>

resources/views/layouts/navbar.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Word Power</title>
</head>
<body>
{{-- Navbar --}}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand text-light">Word Power</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {{ request()->path() === 'words' ? 'active' : '' }}">
          <a class="nav-link" href="{{ route('words.index') }}">Home</a>
        </li>
        {{-- <li class="nav-item  {{ request()->path() === 'test' ? 'active' : '' }}"> --}}
          {{-- <a class="nav-link" href="{{ route('words.test') }}">Take test</a> --}}
          {{-- <a class="nav-link"  data-toggle="modal" data-target="#exampleModal">Take test</a> --}}
        {{-- </li> --}}
        {{-- <li class="nav-item  {{ request()->path() === 'check' ? 'active' : '' }}"> --}}
            {{-- <a class="nav-link" href="{{ route('words.check') }}">Check Word</a> --}}
            {{-- <a class="nav-link"  data-toggle="modal" data-target="#exampleModal2">Check Word</a> --}}
          {{-- </li> --}}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Random Word Checks
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <a class="dropdown-item"  data-toggle="modal" data-target="#exampleModal">MCQs Check</a>
              <a class="dropdown-item"  data-toggle="modal" data-target="#exampleModal2">Show Word Check</a>

            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Tests
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">

              <a class="dropdown-item"  data-toggle="modal" data-target="#exampleModal3">MCQs Test</a>
              <a class="dropdown-item"  data-toggle="modal" data-target="#exampleModal4">Show Word Test</a>

            </div>
          </li>
        <li class="nav-item">
            <a href="{{ route('words.create') }}" class="nav-link text-warning {{ request()->path() === 'words/create' ? 'font-weight-bold' : '' }}">Add New Word</a>
        </li>

      </ul>

    </div>
    <form action="{{ route('words.index') }}" class="form-inline my-2 my-lg-0" method="GET">
        @csrf
        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search any word" aria-label="Search" value="{{ request('search') }}">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
  </nav>
{{-- /Navbar --}}

resources/views/mcq.blade.php
@extends('layouts.app')
@section('content')

@foreach ($question_paper as $key=>$value)
    <div class="d-flex justify-content-center">

        <div class="card mt-5 w-75">
            <div class="card-header bg-dark text-light">
              <p class="font-weight-bold m-0">{{$loop->index + 1}}</p>
            </div>
            <div class="card-body">


                    <fieldset class="form-group">
                      <div class="row">
                        <div class="col-md-5">
                            <input id="word-id" type="hidden" value="{{ $value[4] }}">
                            <h1 class="text-capitalize">{{ $key }}</h1>
                        </div>
                        <div class="col-sm-7">
                          @for ($m=0; $m<4; $m++)
                          <div class="form-check">
                            <input id="radio{{$loop->index . $m}}" class="form-check-input" type="radio" name="radioans{{$loop->index}}" value="{{ $value[$m][1] }}">
                            <label class="form-check-label" for="radio{{$loop->index . $m}}">

                              <p class="text-capitalize">{{ $value[$m][0] }}</p>
                            </label>
                          </div>

                          @endfor
                          <div class="col-sm-8">
                            <p id="ans{{$loop->index}}" class="m-0"></p>
                          </div>
                        </div>
                      </div>
                    </fieldset>
            </div>
          </div>

    </div>
    @endforeach

      <div class="mt-5 d-flex justify-content-center align-content-center">
        <button id="btn-submit" class="btn btn-primary m-0">Submit</button>
      </div>
      <p id="page-ans" class="mt-3 text-center"></p>

@endsection

@section('footer-val','mt-3')
@section('scripts')
<script>
  ansPaper = [];
  @foreach ($question_paper as $key=>$value)
    ansPaper.push("{{ $value[4] }}");
  @endforeach

  flag=true;
  len_of_questionPaper = <?php echo (sizeof($question_paper))?>;
  $("#btn-submit").click(function(){
    var ans = $("input[name^='radioans']:checked");
    if(ans.length != len_of_questionPaper)
    {
        alert('Please answer all the questions');
            return;
    }
    else
    {
        for(i=0; i<len_of_questionPaper; i++)
        {
            if(ansPaper[i] == ans[i].value)
            {
                // console.log(i + " is right");
                $("#ans"+i).text("Yes!! Its Correct!!");
                $('#ans'+i).removeClass("text-danger");
                $('#ans'+i).addClass("text-success");
            }
            else
            {
                // console.log(i + " is wrong");
                flag=false;
                $('#ans'+i).text("Oh No! Its Wrong");
                $('#ans'+i).removeClass("text-success");
                $('#ans'+i).addClass("text-danger");
            }
        }
        if(!flag)
        {
            $("#page-ans").text("Something is wrong!");
            $('#page-ans').removeClass("text-success");
            $("#page-ans").addClass("text-danger");
        }
        else
        {
            $("#page-ans").text("Everything is right!");
            $('#page-ans').addClass("text-success");
            $("#page-ans").removeClass("text-danger");
        }
        flag=true;
        // console.log('Here');
    }

  });
</script>
@endsection

resources/views/range.blade.php
@extends('layouts.app')
@section('content')

      {{-- Index --}}
      @if($errors->any())
            <div class="mx-auto" style="width: 400px;">
                @foreach ($errors->all() as $error)
                <p class="text-danger m-0"> {{ $error }}</p>
            @endforeach
            </div>
        @endif
      <div class="range d-flex justify-content-center mt-3">
       <div>
        <form class="form-inline" action="{{ route('words.rangeCheck') }}" method="POST">
            @csrf
            <div class="form-group mx-sm-3 mb-2">
                <input type="number" class="form-control" id="from" name='From-field' placeholder="From" value="{{ old('From-field') }}">
              </div>
            <div class="form-group mx-sm-3 mb-2">
              <input type="number" class="form-control" id="to" name='To-field' placeholder="To" value="{{ old('To-field') }}">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Search</button>
          </form>
       </div>
     </div>



      <div class="row">
        @foreach ($words as $word)
        <div class="col-sm-6 mt-3">
            <div class="card p-0">
                <div class="card-header bg-dark text-light">
                  <p class="font-weight-bold m-0">Word {{ $word->id }}</p>
                </div>
                <div class="card-body">
                  <h2 class="card-title text-capitalize">{{ $word->name }}</h2>
                  <p class="card-text text-capitalize">{{ $word->meaning }}</p>
                  <a href="{{ route('words.edit', $word->id) }}" class="btn btn-warning">Edit</a>
                </div>
              </div>
        </div>
        @endforeach
      </div>
@endsection
@section('footer-val','mt-3')